# Generated by Django 5.0.2 on 2024-05-05 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='status',
            new_name='status_id',
        ),
    ]
