# Generated by Django 5.0.2 on 2024-05-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(to='articles.author', verbose_name='نویسنده مقاله'),
        ),
    ]
